#!/bin/sh

# PROVIDE: website
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name=website
rcvar=website_enable

load_rc_config $name

: ${website_enable="YES"}
: ${sites_home_dir:="/root/sites"}

pidfile="/var/run/site_${name}.pid"
procname=/usr/local/share/${name}/${name}
# https://man.freebsd.org/cgi/man.cgi?query=daemon
command=/usr/sbin/daemon
command_args="-c -f -P ${pidfile} -r /usr/local/bin/podman run --rm --network=host website"

run_rc_command "$1"
